title:        Farhad Sotothe
tagline:      'Farhad Sotothe'
description:  'Student of Computer Science at Iranian academic center for education, culture and research, Mashhad'
url:    http://sotothe.github.io
version:      1.1.1
author:
  name:       Farhad Sotothe
  email:      so.to.the@gmail.com
permalink:    pretty
pygments:     true
paginate:     6
gems: ["jekyll-paginate"]