title:        فرهاد ستوده
tagline:      'فرهاد ستوده'
description:  'توضیحات'
url:    http://sotothe.github.io
version:      1.1.1
author:
  name:       فرهاد ستوده
  email:      so.to.the@gmail.com
permalink:    pretty
pygments:     true
paginate:     6
gems: ["jekyll-paginate"]
